# Numpy

why Numpy is Preffered over array Modult in the Python ? <br>
Numpy is faster than the pyhton array model,<br>
Numpy has many supporting liberary as a result for the mathamitical operation for larger data Numpy id preffered over the python array model

In [2]:
 import numpy as np  # importing the libreary

### Converting list into an Numpy array 
for the tuple is also the same way

In [13]:
lst = [10,20,30,40]
lst

[10, 20, 30, 40]

In [14]:
array1 = np.array(lst)
print(array1.dtype)
print(array1)

int32
[10 20 30 40]


Remember while converting a list to numpy array if the list have any string value every value will be converted to a string  

In [15]:
lst = [10,20,30,40,"string"]
array1 = np.array(lst)
# type(array1)
print(array1)
print(array1.dtype)

['10' '20' '30' '40' 'string']
<U11


## arange 

arange is nothing but range itself in numpy

syntax<br>
<b>np.arange(start,end,interval)</b><br>
output will be <b>start</b> to <b>(end-interval)</b><br>  default interval value will be 1<br>
Note: End will not be include (<b>End is exclusive</b> in the arange)

In [22]:
np.arange(1,10,.1).size
# np.size

90

## linspace

linspace is similar to arage<br>
syntax <br>
<b>np.linspace(start,end,no_of_items_to_generate_form_start_end)</b><br>
output will be <b>start</b> to <b>(end)</b><br>  
default no_of_items_to_generate_form_start_end value will be 1 <br>
Note: mentioned no of items will be generated from the <b>start to end (Including end as well)</b> (<b>End is inclusive</b> in the linspace)

In [30]:
np.linspace(1,10,90)

array([ 1.        ,  1.1011236 ,  1.20224719,  1.30337079,  1.40449438,
        1.50561798,  1.60674157,  1.70786517,  1.80898876,  1.91011236,
        2.01123596,  2.11235955,  2.21348315,  2.31460674,  2.41573034,
        2.51685393,  2.61797753,  2.71910112,  2.82022472,  2.92134831,
        3.02247191,  3.12359551,  3.2247191 ,  3.3258427 ,  3.42696629,
        3.52808989,  3.62921348,  3.73033708,  3.83146067,  3.93258427,
        4.03370787,  4.13483146,  4.23595506,  4.33707865,  4.43820225,
        4.53932584,  4.64044944,  4.74157303,  4.84269663,  4.94382022,
        5.04494382,  5.14606742,  5.24719101,  5.34831461,  5.4494382 ,
        5.5505618 ,  5.65168539,  5.75280899,  5.85393258,  5.95505618,
        6.05617978,  6.15730337,  6.25842697,  6.35955056,  6.46067416,
        6.56179775,  6.66292135,  6.76404494,  6.86516854,  6.96629213,
        7.06741573,  7.16853933,  7.26966292,  7.37078652,  7.47191011,
        7.57303371,  7.6741573 ,  7.7752809 ,  7.87640449,  7.97

In [ ]:
np.linspace(1,10,90).size

## reshape

reshape is to change the order in the of the array.<br>
we can make 1d array to 2d (Note while converting there must those many no of elements to convert 1d to 2d)<br>
we can change 2d diamension like (2,4) to (4,2) 


In [37]:
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

<b>Note</b>: if you are not aware of the diamention that has to be given to the  data
      we could assigin value for colum or row  then we can assign negative no for the other one the os will decide to set the matrix


In [47]:
np.arange(1000).reshape(100,-1) 
# in this example for colum we have give a neagtive no as a result system has take 10 as per the rows and data avaliable


array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99],
       [100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
       [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
       [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
       [150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
       [160, 161, 162, 163, 164, 165, 166, 167, 168, 169

## zeros

In [41]:
np.zeros(10).reshape(2,5)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

## ones

In [42]:
np.ones(10).reshape(2,5)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## eye (Identity matrix)

In [44]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Transponseof a matrix
Converting the rows into colums

In [3]:
ind_state = np.array(['KL','KA','TL','AP','TH','MP','MH','UP','DL','HP','WB','RJ'])
print(ind_state.reshape(4,-1))
print(ind_state.reshape(4,-1).T)


[['KL' 'KA' 'TL']
 ['AP' 'TH' 'MP']
 ['MH' 'UP' 'DL']
 ['HP' 'WB' 'RJ']]
[['KL' 'AP' 'MH' 'HP']
 ['KA' 'TH' 'UP' 'WB']
 ['TL' 'MP' 'DL' 'RJ']]


## setting the Order of the matrix while re-shaping it *

In [4]:
ind_state = np.array(['KL','KA','TL','AP','TH','MP','MH','UP','DL','HP','WB','RJ'])
np.reshape(ind_state,(4,-1),order='C')  # Row major format. (Note: by default it will be Row major format)

array([['KL', 'KA', 'TL'],
       ['AP', 'TH', 'MP'],
       ['MH', 'UP', 'DL'],
       ['HP', 'WB', 'RJ']], dtype='<U2')

In [5]:
np.reshape(ind_state,(4,-1),order='F')  # Colum Major format

array([['KL', 'TH', 'DL'],
       ['KA', 'MP', 'HP'],
       ['TL', 'MH', 'WB'],
       ['AP', 'UP', 'RJ']], dtype='<U2')

## Operation using Numpy Array


### Scalar Operation

In [27]:
array1 = np.array([1,2,3,4])
print(array1+2)
print(array1*2)
print(array1-1)
print(array1/2)
array1 = np.array([1,2,3,4]).reshape(2,2)
print(array1+2)
print(array1*2)
print(array1-1)
print(array1/2)

[3 4 5 6]
[2 4 6 8]
[0 1 2 3]
[0.5 1.  1.5 2. ]
[[3 4]
 [5 6]]
[[2 4]
 [6 8]]
[[0 1]
 [2 3]]
[[0.5 1. ]
 [1.5 2. ]]


multiplying of 2 arrays

In [19]:
array1 = np.array([1,2,3,4]).reshape(2,2)
print(array1)
array2 = np.array([5,6,7,8]).reshape(2,2)
print(array2)
array1*array2 # Remember its not giving you the dot product

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


array([[ 5, 12],
       [21, 32]])

Dot Product of the matrix

In [26]:
array1 = np.array([1,2,3,4]).reshape(2,2)
print(array1)
array2 = np.array([5,6,7,8]).reshape(2,2)
print(array2)
# [[1*5+2*7,1*6+2*8],
#  [3*5+4*7,3*6+4*8]]   
#
np.dot(array1,array2)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


array([[19, 22],
       [43, 50]])

### Uniary operation

In [39]:
array1 = np.arange(25).reshape(5,5)
print(array1)
print("--------------Sum-------------------")
print(array1.sum()) # Sum of all the element in the matrix/array
print("--------------Max-------------------")
print(array1.max()) # Max element in the matrix/array
print("--------------Min-------------------")
print(array1.min()) # Min element in the matrix/array

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
--------------Sum-------------------
300
--------------Max-------------------
24
--------------Min-------------------
0


#### To do the Colum/row wise the Uniary Operation

In [38]:
array1 = np.arange(25).reshape(5,5)
print(array1)
# axis = 1 i.e rows
# axis = 0 i.e colum
print("--------------Sum-------------------")
print(np.sum(array1, axis = 1))
print(np.sum(array1, axis = 0))
print("--------------Max-------------------")
print(np.max(array1, axis = 1))
print(np.max(array1, axis = 0))
print("--------------Min-------------------")
print(np.min(array1, axis = 1))
print(np.min(array1, axis = 0))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
--------------Sum-------------------
[ 10  35  60  85 110]
[50 55 60 65 70]
--------------Max-------------------
[ 4  9 14 19 24]
[20 21 22 23 24]
--------------Min-------------------
[ 0  5 10 15 20]
[0 1 2 3 4]


## Check the Univeral functions of the Numpy (Google IT)

## BroadCasting in Numpy  

In [42]:
# Broadcasting 
# 1. at least one array should be of single dimension
# 2. No of elelemnt in single dimension array and no of columns in multi dimension array should be same - row wise broadcasting

# if both the arrays are of 2/3/4... dimensuon
# no Coulmn should be 1 and no of rows should match in both the arrays

a1 = np.arange(30).reshape(6,-1)
print(a1)
a2 = np.array([[10,11,12,13,14],[15,16,17,18,19]])
print(a1+a2)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


ValueError: operands could not be broadcast together with shapes (6,5) (2,5) 

In [46]:
# Case 1

# [[ 0  1  2  3  4]  [10,11,12,13,14]
#  [ 5  6  7  8  9]  [10,11,12,13,14]
#  [10 11 12 13 14]  [10,11,12,13,14]
#  [15 16 17 18 19]  [10,11,12,13,14]
#  [20 21 22 23 24]  [10,11,12,13,14]
#  [25 26 27 28 29]] [10,11,12,13,14]


# [10,11,12,13,14]



# Case 2
# [[ 0  1  2  3  4]   [10 10 10 10 10]
#  [ 5  6  7  8  9]   [11 11 11 11 11]
#  [10 11 12 13 14]   [12 12 12 12 12]
#  [15 16 17 18 19]   [13 13 13 13 13]
#  [20 21 22 23 24]   [14 14 14 14 14]
#  [25 26 27 28 29]]  [15 15 15 15 15]


# [[10],
#  [11],
#  [12],
#  [13],
#  [14],
#  [15]]

# Case 3
# [[10,11,12,13,14],
# [20,21,22,23,24]]

# [[10],
#  [11],
#  [12],
#  [13],
#  [14],
#  [15]]

# [10,11,12,13,14] [10 10 10 10 10]
# [10,11,12,13,14] [11 11 11 11 11]
# [10,11,12,13,14] [12 12 12 12 12]
# [10,11,12,13,14] [13 13 13 13 13]
# [10,11,12,13,14] [14 14 14 14 14]
# [10,11,12,13,14] [15 15 15 15 15]

