##  Views & Copy

In [1]:
import numpy as np

In [2]:
arr1 = np.arange(25)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [4]:
v1 = arr1[2:3]
v1

array([2])

In [6]:
# deep copy
arr1[2] = 222
print(arr1)
print(v1)

[  0   1 222   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24]
[222]


In [8]:
# deep copy of the view
v1[0] = 555
print(arr1)
print(v1)

[  0   1 555   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24]
[555]


Melwin see the example which is mentioned below in the below scenario its not deep copy <br>
v1 = 555<br>
data type of v1 got typecasted to int <br>
To update the array position we need to mention the array position<br>


In [10]:
v2 = arr1.view()
print(v2)

[  0   1 555   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24]


In [11]:
arr1[3] = 333
print(arr1)
print(v2)

[  0   1 555 333   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24]
[  0   1 555 333   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24]


## copy()

In [12]:
arr2 = np.arange(5)
arr2

array([0, 1, 2, 3, 4])

In [14]:
a = arr2
print(a)
c = np.copy(a)
print(c)

[0 1 2 3 4]
[0 1 2 3 4]


In [15]:
arr2[0] = 111
print("arr2",arr2)
print("a",a)
print("c",c)

arr2 [111   1   2   3   4]
a [111   1   2   3   4]
c [0 1 2 3 4]


## Automatic Reshaping

Melwin you already know about this only one of the diamention we can mention as -1 System will reshape as per the avaliable data 

## Stacking or concatenation in an array

In [22]:
arr1 = np.array([['UP', 'MP'],['KA', 'TN']])

arr2 = np.array([['DL', 'RJ'],['KL','AP']])

arr1.shape
arr2.shape

(2, 2)

In [18]:
np.concatenate((arr1,arr2)) # By Default row wise

array([['UP', 'MP'],
       ['KA', 'TN'],
       ['DL', 'RJ'],
       ['KL', 'AP']], dtype='<U2')

In [20]:
np.concatenate((arr1,arr2), axis = 0) # row wise axis = 0

array([['UP', 'MP'],
       ['KA', 'TN'],
       ['DL', 'RJ'],
       ['KL', 'AP']], dtype='<U2')

In [21]:
np.concatenate((arr1,arr2), axis = 1)

array([['UP', 'MP', 'DL', 'RJ'],
       ['KA', 'TN', 'KL', 'AP']], dtype='<U2')

In [23]:
np.vstack((arr1,arr2))

array([['UP', 'MP'],
       ['KA', 'TN'],
       ['DL', 'RJ'],
       ['KL', 'AP']], dtype='<U2')

In [24]:
np.hstack((arr1,arr2))

array([['UP', 'MP', 'DL', 'RJ'],
       ['KA', 'TN', 'KL', 'AP']], dtype='<U2')